hosted-ce-setup.sh
https://opensciencegrid.atlassian.net/browse/SOFTWARE-3906
Helm chart update: https://github.com/slateci/slate-catalog/pull/189
=> Add developer mode (SOFTWARE-3906)

hosted-ce-setup.sh
Based off of the route endpoints in the job router configuration
=> Create SSH configuration for multiple VOs (SOFTWARE-3908)

25-hosted-ce-setup.sh, 30-remote-site-setup.sh
We removed the `LOCAL_ATTRIBUTES_FILE` here: https://github.com/slateci/slate-catalog/pull/198
=> Misc fixups (SOFTWARE-3729)

25-hosted-ce-setup.sh, 30-remote-site-setup.sh
=> Automatically retrieve the remote OS major ver (SOFTWARE-3729)

51-gratia.conf, Dockerfile
https://jira.opensciencegrid.org/browse/SOFTWARE-3841
Packages are currently picked up from minefield so this should be good to go
=> Drop Gratia schedd cron config now provided by osg-ce-bosco

25-hosted-ce-setup.sh, 30-remote-site-setup.sh
The cron was failing so the remote WN client, CAs, and CRLs weren't being updated
=> Fix WN client schedd cron running as the 'condor' user

30-remote-site-setup.sh
=> Allow non-root users to write to /var/log/condor-ce

30-remote-site-setup.sh
=> Run SSH in quiet mode for remote commands

30-remote-site-setup.sh
Auto-detection was failing at TACC. Also consolidate expected env var comment.
=> Use REMOTE_OS_VER from the environment

30-remote-site-setup.sh
This reverts commit 801bd90b1e946565e90a56e244fad8690e9e1f6e.
=> Revert "Use REMOTE_OS_VER from the environment"

30-remote-site-setup.sh
This should be what's needed to patch up our container for TACC.
=> TACC fixes

Dockerfile
This includes HTCondor 8.9.6, which has SciToken/JWT support
=> Also install from upcoming minefield

30-remote-site-setup.sh, 99-container.conf, Dockerfile, remote-wn-client-wrapper.sh
=> Skip remote WN client seutp for CVMFS WN clients (SOFTWARE-3981)

bosco-override-setup.sh
@mmascher and @jdost321 ran into host verification failures when accessing a Git SSH endpoint
I wish you could chain param expansions...
=> Pre-scan Git SSH hosts

30-remote-site-setup.sh, bosco_cluster, ssh_q.patch
=> Add the ability for users to specify the remote bosco install dir (SOFTWARE-4095)

Dockerfile, condor_ce_jobmetrics
This is [condor_ce_jobmetrics](https://github.com/htcondor/htcondor-ce/blob/f6f61a9a380bef26d89f3b52211babbef8cd2e69/src/condor_ce_jobmetrics), overriding the one in the currently-released htcondor-ce-view package, until the next release.
=> pull in condor_ce_jobmetrics prior to release (SOFTWARE-4183)

30-remote-site-setup.sh
e.g. [SSH error messages](https://github.com/opensciencegrid/docker-hosted-ce/blob/master/bosco_cluster#L837)
=> Enable bosco_cluster debug output

30-remote-site-setup.sh, bosco-override-setup.sh
https://opensciencegrid.atlassian.net/browse/SOFTWARE-4281
=> Fix handling of SSH failures (SOFTWARE-4281)

30-remote-site-setup.sh
@mmascher should fix https://support.opensciencegrid.org/a/tickets/65283
=> Handle multiple host keys

overrides/bosco_cluster
This is the culprit of some breakages at Expanse
=> Fix bosco_cluster for EL8

30-remote-site-setup.sh
bosco_cluster and the batch_gahp should already reuse connections
=> Enable SSH session reuse for remote node setup

30-remote-site-setup.sh
Includes #79 so I'll turn this into a full PR and request reviewers when that PR's been sorted out
=> Skip remote WN tarball installs for non-RHEL hosts (SOFTWARE-4329)

30-remote-site-setup.sh
=> Specify $HOME for Singularity

30-remote-site-setup.sh
@efajardo this should fix your pilot issue
=> Restore remote homedir detection

Dockerfile, overrides/bosco_findplatform
https://github.com/htcondor/htcondor/pull/135. Can be merged once @timtheisen updates the 1.3 symlink
=> Use upstream bosco_findplatform (SOFTWARE-4337)

Dockerfile
And bonus removal of superfluous `ENTRYPOINT`
=> Mirrors are slow

Dockerfile
Same changes work here https://github.com/opensciencegrid/docker-compute-entrypoint!
=> Use HTCondor-CE 5.0.0 from upcoming (SOFTWARE-4445)

Dockerfile, overrides/HTCONDOR-242.remote-os-detection.patch
Carry a patch until HTCONDOR-242 is released
=> Fix Ubuntu20 remote OS detection (SOFTWARE-4463)
